# concept_config.py
# -*- coding: utf-8 -*-

"""
Concept / Term / Taxonomy configuration.

Core graph model:

(:Chunk)-[:MENTIONS_TERM]->(:Term)-[:NORMALIZED_TO]->(:Concept)
(:Concept)-[:HAS_SUBCONCEPT]->(:Concept)
(:CandidateTerm)-[:SUGGESTED_FOR]->(:Concept)

This file is intentionally pure config.
"""

CONCEPTS = [
    {
        "concept_id": "financial_regulation",
        "name": "金融監管",
        "category": "root",
        "description": "銀行、金融機構及相關活動的監管要求和監督框架。",
        "level": 0,
        "source": "manual",
    },
    {
        "concept_id": "corporate_governance",
        "name": "企業管治",
        "category": "governance",
        "description": "董事局、高級管理層、內部監控和問責安排等企業管治要求。",
        "level": 1,
        "source": "manual",
    },
    {
        "concept_id": "risk_management",
        "name": "風險管理",
        "category": "risk",
        "description": "識別、評估、監察、控制和匯報風險的制度、程序和責任。",
        "level": 1,
        "source": "manual",
    },
    {
        "concept_id": "credit_risk",
        "name": "信貸風險",
        "category": "risk",
        "description": "因借款人或交易對手未能履行責任而導致損失的風險。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "market_risk",
        "name": "市場風險",
        "category": "risk",
        "description": "因利率、匯率、股票價格、商品價格或其他市場因素變動而導致損失的風險。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "operational_risk",
        "name": "操作風險",
        "category": "risk",
        "description": "因內部程序、人員、系統不足或失誤，或外部事件而導致損失的風險。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "liquidity_risk",
        "name": "流動性風險",
        "category": "risk",
        "description": "機構未能在到期時履行付款責任，或只能以高成本取得資金的風險。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "aml_cft",
        "name": "反洗錢及打擊恐怖分子資金籌集",
        "category": "aml_cft",
        "description": "防止、偵測和匯報洗錢及恐怖分子資金籌集活動的監管要求。",
        "level": 1,
        "source": "manual",
    },
    {
        "concept_id": "board",
        "name": "董事局",
        "category": "governance",
        "description": "負責監督機構策略、風險管理、內部監控和企業管治的最高治理機構。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "senior_management",
        "name": "高級管理層",
        "category": "governance",
        "description": "負責執行董事局策略、建立和維持風險管理及內部監控制度的管理層。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "internal_control",
        "name": "內部監控",
        "category": "control",
        "description": "確保業務運作、財務匯報、合規和風險控制有效性的政策及程序。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "audit",
        "name": "審計",
        "category": "control",
        "description": "對機構管治、風險管理、內部監控或財務資料進行獨立檢查和評估的活動。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "compliance",
        "name": "合規",
        "category": "compliance",
        "description": "遵守法律、規例、監管要求、內部政策和行業標準的安排。",
        "level": 1,
        "source": "manual",
    },
    {
        "concept_id": "cdd",
        "name": "客戶盡職審查",
        "category": "aml_cft",
        "description": "識別和核實客戶身份、了解業務關係目的、評估客戶洗錢及恐怖分子資金籌集風險的程序。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "ongoing_monitoring",
        "name": "持續監察",
        "category": "aml_cft",
        "description": "在業務關係期間持續監察客戶活動、交易和風險狀況的程序。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "suspicious_transaction",
        "name": "可疑交易報告",
        "category": "aml_cft",
        "description": "識別、評估和匯報可能涉及洗錢或恐怖分子資金籌集的可疑交易。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "sanctions_screening",
        "name": "制裁篩查",
        "category": "aml_cft",
        "description": "將客戶、交易對手、受益人或交易資料與制裁名單進行比對的程序。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "beneficial_owner",
        "name": "實益擁有人",
        "category": "aml_cft",
        "description": "最終擁有或控制客戶，或代表其進行交易或活動的自然人。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "pep",
        "name": "政治人物",
        "category": "aml_cft",
        "description": "因擔任重要公職而可能帶來較高洗錢或貪污風險的人士及其相關人士。",
        "level": 2,
        "source": "manual",
    },
    {
        "concept_id": "risk_based_approach",
        "name": "風險為本方法",
        "category": "aml_cft",
        "description": "根據客戶、產品、服務、交易、地域或其他因素的風險程度調整管控措施的方法。",
        "level": 2,
        "source": "manual",
    },
]

TERMS = [
    {
        "term_id": "term_financial_regulation_zh",
        "text": "金融監管",
        "concept_id": "financial_regulation",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_corporate_governance_zh",
        "text": "企業管治",
        "concept_id": "corporate_governance",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_corporate_governance_en",
        "text": "corporate governance",
        "concept_id": "corporate_governance",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_risk_management_zh",
        "text": "風險管理",
        "concept_id": "risk_management",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_risk_management_en",
        "text": "risk management",
        "concept_id": "risk_management",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_credit_risk_zh",
        "text": "信貸風險",
        "concept_id": "credit_risk",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_credit_risk_en",
        "text": "credit risk",
        "concept_id": "credit_risk",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_market_risk_zh",
        "text": "市場風險",
        "concept_id": "market_risk",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_market_risk_en",
        "text": "market risk",
        "concept_id": "market_risk",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_operational_risk_zh",
        "text": "操作風險",
        "concept_id": "operational_risk",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_operational_risk_en",
        "text": "operational risk",
        "concept_id": "operational_risk",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_liquidity_risk_zh",
        "text": "流動性風險",
        "concept_id": "liquidity_risk",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_liquidity_risk_en",
        "text": "liquidity risk",
        "concept_id": "liquidity_risk",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_aml_zh",
        "text": "反洗錢",
        "concept_id": "aml_cft",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_aml_cft_zh",
        "text": "反洗錢及打擊恐怖分子資金籌集",
        "concept_id": "aml_cft",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_aml_en",
        "text": "anti-money laundering",
        "concept_id": "aml_cft",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_aml_abbr",
        "text": "AML",
        "concept_id": "aml_cft",
        "language": "en",
        "match_type": "word",
        "source": "manual",
    },
    {
        "term_id": "term_cft_zh",
        "text": "打擊恐怖分子資金籌集",
        "concept_id": "aml_cft",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_cft_en",
        "text": "counter-financing of terrorism",
        "concept_id": "aml_cft",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_cft_abbr",
        "text": "CFT",
        "concept_id": "aml_cft",
        "language": "en",
        "match_type": "word",
        "source": "manual",
    },
    {
        "term_id": "term_cdd_zh",
        "text": "客戶盡職審查",
        "concept_id": "cdd",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_cdd_short_zh",
        "text": "盡職審查",
        "concept_id": "cdd",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_cdd_en",
        "text": "customer due diligence",
        "concept_id": "cdd",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_cdd_abbr",
        "text": "CDD",
        "concept_id": "cdd",
        "language": "en",
        "match_type": "word",
        "source": "manual",
    },
    {
        "term_id": "term_ongoing_monitoring_zh",
        "text": "持續監察",
        "concept_id": "ongoing_monitoring",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_ongoing_monitoring_en",
        "text": "ongoing monitoring",
        "concept_id": "ongoing_monitoring",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_suspicious_transaction_zh",
        "text": "可疑交易",
        "concept_id": "suspicious_transaction",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_suspicious_transaction_report_zh",
        "text": "可疑交易報告",
        "concept_id": "suspicious_transaction",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_str_en",
        "text": "suspicious transaction report",
        "concept_id": "suspicious_transaction",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_str_abbr",
        "text": "STR",
        "concept_id": "suspicious_transaction",
        "language": "en",
        "match_type": "word",
        "source": "manual",
    },
    {
        "term_id": "term_sanctions_screening_zh",
        "text": "制裁篩查",
        "concept_id": "sanctions_screening",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_sanctions_screening_en",
        "text": "sanctions screening",
        "concept_id": "sanctions_screening",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_beneficial_owner_zh",
        "text": "實益擁有人",
        "concept_id": "beneficial_owner",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_beneficial_owner_en",
        "text": "beneficial owner",
        "concept_id": "beneficial_owner",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_pep_zh",
        "text": "政治人物",
        "concept_id": "pep",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_pep_en",
        "text": "politically exposed person",
        "concept_id": "pep",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_pep_abbr",
        "text": "PEP",
        "concept_id": "pep",
        "language": "en",
        "match_type": "word",
        "source": "manual",
    },
    {
        "term_id": "term_risk_based_approach_zh",
        "text": "風險為本方法",
        "concept_id": "risk_based_approach",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_risk_based_approach_en",
        "text": "risk-based approach",
        "concept_id": "risk_based_approach",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_board_zh",
        "text": "董事局",
        "concept_id": "board",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_board_zh_alt",
        "text": "董事會",
        "concept_id": "board",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_board_en",
        "text": "board of directors",
        "concept_id": "board",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_senior_management_zh",
        "text": "高級管理層",
        "concept_id": "senior_management",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_senior_management_en",
        "text": "senior management",
        "concept_id": "senior_management",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_internal_control_zh",
        "text": "內部監控",
        "concept_id": "internal_control",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_internal_control_en",
        "text": "internal control",
        "concept_id": "internal_control",
        "language": "en",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_audit_zh",
        "text": "審計",
        "concept_id": "audit",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_internal_audit_zh",
        "text": "內部審計",
        "concept_id": "audit",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_audit_en",
        "text": "audit",
        "concept_id": "audit",
        "language": "en",
        "match_type": "word",
        "source": "manual",
    },
    {
        "term_id": "term_compliance_zh",
        "text": "合規",
        "concept_id": "compliance",
        "language": "zh",
        "match_type": "phrase",
        "source": "manual",
    },
    {
        "term_id": "term_compliance_en",
        "text": "compliance",
        "concept_id": "compliance",
        "language": "en",
        "match_type": "word",
        "source": "manual",
    },
]

TAXONOMY = [
    {
        "parent_concept_id": "financial_regulation",
        "child_concept_id": "corporate_governance",
    },
    {
        "parent_concept_id": "financial_regulation",
        "child_concept_id": "risk_management",
    },
    {
        "parent_concept_id": "financial_regulation",
        "child_concept_id": "aml_cft",
    },
    {
        "parent_concept_id": "financial_regulation",
        "child_concept_id": "compliance",
    },
    {
        "parent_concept_id": "corporate_governance",
        "child_concept_id": "board",
    },
    {
        "parent_concept_id": "corporate_governance",
        "child_concept_id": "senior_management",
    },
    {
        "parent_concept_id": "corporate_governance",
        "child_concept_id": "internal_control",
    },
    {
        "parent_concept_id": "corporate_governance",
        "child_concept_id": "audit",
    },
    {
        "parent_concept_id": "risk_management",
        "child_concept_id": "credit_risk",
    },
    {
        "parent_concept_id": "risk_management",
        "child_concept_id": "market_risk",
    },
    {
        "parent_concept_id": "risk_management",
        "child_concept_id": "operational_risk",
    },
    {
        "parent_concept_id": "risk_management",
        "child_concept_id": "liquidity_risk",
    },
    {
        "parent_concept_id": "aml_cft",
        "child_concept_id": "cdd",
    },
    {
        "parent_concept_id": "aml_cft",
        "child_concept_id": "ongoing_monitoring",
    },
    {
        "parent_concept_id": "aml_cft",
        "child_concept_id": "suspicious_transaction",
    },
    {
        "parent_concept_id": "aml_cft",
        "child_concept_id": "sanctions_screening",
    },
    {
        "parent_concept_id": "aml_cft",
        "child_concept_id": "beneficial_owner",
    },
    {
        "parent_concept_id": "aml_cft",
        "child_concept_id": "pep",
    },
    {
        "parent_concept_id": "aml_cft",
        "child_concept_id": "risk_based_approach",
    },
]

STOPWORDS = [
    "本指引",
    "有關",
    "相關",
    "包括",
    "以下",
    "應該",
    "必須",
    "可以",
    "例如",
    "資料",
    "文件",
    "規定",
    "程序",
    "措施",
    "進行",
    "提供",
    "確保",
    "根據",
    "如有",
    "以及",
    "及其",
    "香港",
    "銀行",
    "機構",
    "認可",
    "認可機構",
    "金管局",
    "監管",
    "要求",
    "情況",
    "可能",
    "需要",
    "應用",
    "使用",
    "作出",
    "進一步",
    "任何",
    "所有",
    "其他",
    "一般",
    "主要",
    "若干",
    "各項",
    "不同",
    "適當",
    "有效",
    "充分",
    "定期",
    "附錄",
    "第",
    "頁",
]